using MessageProtocol.CodeGenerator.Metadata;
using System.Text;

namespace MessageProtocol.CodeGenerator.Generate
{
    internal static partial class MessageSerializeCodeEmitter
    {
        /// <summary>Generated-file header: usings and namespace.</summary>
        internal static class Header
        {
            public static string Emit(TypeMetadata typeMeta, out bool hasNamespace)
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine("using MessageProtocol.Serialize;");
                sb.AppendLine();

                string namespaceName = typeMeta.Symbol.ContainingNamespace.ToDisplayString();
                hasNamespace = !string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>";
                if (hasNamespace)
                {
                    sb.AppendLine($"namespace {namespaceName}");
                    sb.AppendLine("{");
                }

                return sb.ToString();
            }

            public static string EmitCloseNamespace()
            {
                var sb = new StringBuilder();
                sb.AppendLine();
                sb.AppendLine("}");
                return sb.ToString();
            }
        }
    }
}
